config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  root 'home#index'

  resources :filmes, :generos, :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filme.rb
class Filme < ApplicationRecord
	has_attached_file :imagem, :styles => {:medium => "300x300>", :thumb => "100x100>" }, :default_url=> :set_default_url
	validates_attachment_content_type :imagem, content_type: /\Aimage\/.*\z/
    belongs_to :genero
		belongs_to :user
    validates :titulo, presence:{:message=>"Campo Título é obrigatório"}
		validates :genero_id, presence:{:message=>"Campo Gênero é obrigatório"}
    paginates_per 8

		private

	 def set_default_url
		 "/images/:style/placeholder.png"
	 end
end

app/models/genero.rb
class Genero < ApplicationRecord
	paginates_per 8
    has_many :filmes
		has_many :user, through: :filme
		validates :nome, presence:{:message=>"Campo Nome é obrigatório"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :filmes
  has_many :generos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/filmes_controller.rb
    class FilmesController < ApplicationController

        before_action :authenticate_user!
        before_action :set_params, only: [:edit, :show, :update, :destroy]

        def index
            @filmes = Filme.where(user_id: current_user.id).page params[:page]
        end

        def new
            @filme = Filme.new
            @filme.user_id = current_user.id
        end

        def edit
        end

        def update
            respond_to do |format|
                if @filme.update(filme_params)
                    format.html { redirect_to filmes_path, notice:'Filme atualizado com sucesso'}
                 else
                  format.html { render action: "edit" }
              end
          end
       end

      def show

      end

      def create
         @filme = Filme.create(filme_params)
             respond_to do |format|
                 if @filme.save
                  format.html { redirect_to filmes_path, notice:'Filme salvo com sucesso' }
                else
                  format.html { render action: "new"  }
              end
          end
      end

    def destroy
        if @filme.destroy
          flash[:notice] = "Filme excluído com sucesso"
          redirect_to filmes_path
        end
    end

    private

        def set_params
          @filme = Filme.find(params[:id])
        end

        def filme_params
          params.require(:filme).permit(:titulo, :cartaz, :sinopse, :diretor, :data_lancamento, :genero_id, :produtora, :imagem, :user_id)
        end
    end

app/controllers/generos_controller.rb
    class GenerosController < ApplicationController

    	before_action :authenticate_user!
    	before_action :set_params, only:[:edit, :show, :update, :destroy]

      def index
      	@generos= Genero.where(user_id: current_user.id).page params[:page]
      end

      def new
      	@genero = Genero.new
        @genero.user_id = current_user.id
      end

      def create
      	@genero = Genero.create(genero_params)
      	if @genero.save
      		flash[:notice] = "Gênero salvo com sucesso"
      		redirect_to generos_path
      	end
      end

      def edit
      end

      def update

      	if @genero.update(genero_params)
      		flash[:notice] = "Gênero atualizado com sucesso"
      		redirect_to generos_path
      	end

      end

      def show
      end

      def destroy
      	if @genero.destroy
      		flash[:notice] = "Gênero excluído com sucesso"
      		redirect_to generos_path
      	end
      end

      private

      	def set_params
      		@genero = Genero.find(params[:id])
      	end

      	def genero_params
      		params.require(:genero).permit(:nome, :user_id)
      	end
    end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @images_filmes = Filme.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/helpers/genero_helper.rb
module GeneroHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/filmes/_form.html.haml
=simple_form_for @filme do |f|
	= f.error_notification
	.form-inputs
	=f.input :titulo
	=f.input :imagem, as: :file
	=f.input :sinopse, as: :text
	=f.input :diretor
	=f.input :data_lancamento, as: :date, formats: :only_year
	=f.association :genero, label_method: :nome, prompt: "Selecione um gênero"
	=f.input :user_id, as: :hidden, selected: @filme
	=f.input :produtora
	=f.button :submit, "Salvar Filme", class:'btn btn-primary'

app/views/filmes/edit.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title Editar Filme
  .panel-body
    = render 'form'

app/views/filmes/index.html.haml
- if @filmes.size != nil
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Título
        %th Diretor
        %th Lançamento
        %th Gênero
        %th Produtora
    %tbody
    - @filmes.each do |filme|
      %tr
        %td=filme.titulo
        %td=filme.diretor
        %td=l(filme.data_lancamento, formats: :only_year)
        %td=filme.genero.nome
        %td=filme.produtora
        %td= link_to 'Detalhes', filme_path(filme), class:'btn-sm btn-info'
        %td= link_to 'Editar', edit_filme_path(filme), class:'btn-sm btn-success'
        %td= link_to 'Delete', filme, class:'btn-sm btn-danger', :method => :delete, :data => { :confirm => 'Deseja realmente excluir esse filme?' }
  .col.md-6.col-md-offset-5
    =paginate @filmes
- else
  %p= "Nenhum registro encontrado."

app/views/filmes/new.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title Novo Filme
  .panel-body
    = render 'form' 

app/views/filmes/show.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title=@filme.titulo
  .panel-body
    .row.md-6.col-md-4
      =image_tag @filme.imagem.url(:original)
    .col.md-6.col-md-offset-3
      %h4="Sinopse"
      %p=@filme.sinopse
      %h4="Diretor"
      %p=@filme.diretor
      %h4="Gênero"
      %p=@filme.genero.nome
      %h4="Ano Lançamento"
      %p=l(@filme.data_lancamento, formats: :only_year)
      %h4="Produtora"
      %p=@filme.produtora
      =link_to 'Ver Todos', filmes_path, class:'btn btn-success'

app/views/generos/_form.html.haml
=simple_form_for @genero do |f|
	= f.error_notification
	.form-inputs
	=f.input :nome
	=f.input :user_id, as: :hidden, selected: @genero
	=f.button :submit, "Salvar Gênero", class:'btn btn-primary'

app/views/generos/edit.html.haml
=render 'form'

app/views/generos/index.html.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Nome
  %tbody
  - @generos.each do |genero|
    %tr
      %td=genero.nome
      %td= link_to 'Editar', edit_genero_path(genero), class:'btn-sm btn-success'
      %td= link_to 'Delete', genero, class:'btn-sm btn-danger', :method => :delete, :data => { :confirm => 'Deseja realmente excluir esse gênero?' }
.col.md-6.col-md-offset-5
  =paginate @generos

app/views/generos/new.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title Novo Gênero
  .panel-body
    = render 'form' 

app/views/generos/show.html.haml
%h1 Generos#show
%p Find me in app/views/generos/show.html.erb

app/views/home/index.html.haml
.container
  .jumbotron
    %h1 Catálago Filmes
    %p
      Catálago Filmes é um sistema para catalogar seus filmes favoritos,
      no qual você poderá consultar todas as informações dos filmes cadastrados
      na base de dados do sistema.

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Filmes"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  %body
    .navbar.navbar-inverse.navbar-static-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/home/index"} Catálago Filmes
        .navbar-collapse.collapse.navbar-responsive-collapse
          - if user_signed_in?
            %ul.nav.navbar-nav
              %li= link_to "Novo Filme", "/filmes/new"
              %li= link_to "Filmes", "/filmes"
              %li= link_to "Novo Gênero", "/generos/new"
              %li= link_to "Gêneros", "/generos"
            %ul.nav.navbar-nav.pull-right
              %li= link_to current_user.email 
              %li= link_to "Sair", destroy_user_session_path, method: :delete
          - else
            %ul.nav.navbar-nav.pull-right
              %li= link_to 'Registrar-se', new_user_registration_path
              %li= link_to 'Entrar', user_session_path

    .container
      .row
        = bootstrap_flash
        = yield
      %hr
      %footer
        %h5 © Catálago Filmes 2016
    / /container

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/